esphome:
  name: !secret device # garden-board-test
  platform: ESP8266 # ESP8266 or ESP32
  board: nodemcuv2 # Any ESP8266 or ESP32 board

  includes:
    - SoilMoistureSensor.h

# WiFi connection to base station
wifi:
  ssid: !secret esphome_wifi_ssid
  password: !secret esphome_wifi_password

  manual_ip:
    static_ip: !secret ip_address
    gateway: 192.168.1.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "PC Power Fallback Hotspot"
    password: !secret esphome_ap_password

# captive_portal:

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  password: !secret esphome_api_password

# Enable OTA update via WiFi
ota:
  password: !secret esphome_ota_password

sensor:
  - platform: dht
    pin: D1
    temperature:
      name: "DHT ESP-12E Temperature"
      accuracy_decimals: 0
    humidity:
      name: "DHT ESP-12E Humidity"
    update_interval: 5min
    
  - platform: adc
    pin: A0
    name: "Soil Moisture Sensor"
    unit_of_measurement: "%"
    update_interval: 10min
    id: soil_moisture_sensor
    filters:
    - calibrate_linear:
        - 0.800 -> 0.00
        - 0.400 -> 100.00
    accuracy_decimals: 1

  - platform: custom
    lambda: |-
      auto my_sensor = new SoilMoistureSensor();
      App.register_component(my_sensor);
      return {my_sensor};
    sensors:
      name: "Soil Moisture Sensor2"
      unit_of_measurement: "V"
      accuracy_decimals: 1

# deep sleep
deep_sleep:
  id: deep_sleep_mode
  sleep_duration: 11h
  
time:
  - platform: homeassistant
sun:
  latitude: 5.0410°
  longitude: 75.3815°
  on_sunset:
    - then:
        - deep_sleep.enter: deep_sleep_mode
        - logger.log: Good evening, time to go to sleep!
